### ISSUE TITLE
Resampling module

### ISSUE THREAD

**Issue by CaroAMN** [nf-core/lsmquant#1]
### TODOs:

- [x] update the parameter file with parameters from NMa_template
- [x] compile + containerize matlab code with the adjustments
- [x] add the module
- [ ] test run full pipeline with resampling
