### ISSUE TITLE
Registration module

### ISSUE THREAD

**Issue by CaroAMN** [nf-core/lsmquant#2]
### TODOs:

- [x] update parameter file with parameters from NMa_template
- [x] compile + containerize matlab code with the adjustments
- [ ] add module to workflow
- [ ] test run small dataset ( will not work, because we need a full braibn data set ) 
- [ ] test run with full dataset :fin
